
from sentence_transformers import CrossEncoder
import torch 

_model = None

RERANK_MODEL_PATH = "./models/rerankers/v4"
device = "cuda" if torch.cuda.is_available() else "cpu"

# lazy initialization to load the model only once

# load model
model = CrossEncoder(RERANK_MODEL_PATH, device=device)

test_pairs = [
    ( "multiple sclerosis",  "Symptom Clusters in Systemic Sclerosis ABSTRACT\nAn estimated 2.5 million people worldwide are challenged with managing the disfiguring, debilitating, and often\nunremitting symptoms of systemic sclerosis (SSc; scleroderma). SSc is a rare, chronic multisystem\nautoimmune disease that often leads to high levels of pain, fatigue, sleep disturbance, and altered mood (i.e.,\nanxiety and depressive symptoms) as well as significant functional disability. Prior research in SSc has\nfocused on single symptoms and their effects on patient outcomes. However, little is known about the\nprevalence and impact of multiple co-occurring symptoms, or symptom clusters, and their relationship with\nfunctional disability in patients with SSc. The purpose of this study is to understand the distinct symptom\nexperiences of SSc patients with co-occurring symptoms and their relationship with functional disability to\ninform future development of targeted symptom management interventions. This study aims to: 1) identify\nsubgroups of SSc patients with distinct symptom experiences using a prespecified symptom cluster (i.e., pain,\nfatigue, sleep disturbance, and altered mood); 2) determine the individual characteristics (i.e., demographic\nand clinical characteristics) associated with each symptom cluster subgroup; and, 3) determine the extent to\nwhich symptom cluster subgroups predict functional disability. This descriptive cross-sectional study will use\nexisting symptom data collected at enrollment from the Scleroderma Patient-centered Intervention Network\n(SPIN) Cohort (N=1942), including the Patient-Reported Outcomes Measurement Information System-29\n(PROMIS-29) and the Health Assessment Questionnaire Disability Index (HAQ-DI). Latent profile analysis\n(LPA) will be used to identify subgroups of SSc patients with distinct symptom profiles using a prespecified\nsymptom cluster. Bivariate and multiple regression models will be used to determine individual characteristics\nassociated with each symptom cluster subgroup. Finally, a regression model approach will be used to\ndetermine whether subgroup membership is associated with functional disability. The proposed study supports\nthe National Institute of Nursing Research\u2019s mission and area of strategic focus in symptom science by\nproviding a new lens to SSc symptom research to capture the complexities of the symptom experience through\nexploration of multiple co-occurring symptoms, or symptom clusters, and their effects on functional disability in\nSSc. Findings from this study will inform the next stages of symptom science research (i.e., biomarker\ndiscovery and clinical application) in patients with SSc and has the strong potential to inform symptom science\nin other rare diseases."     
    ),
    ( "systemic sclerosis", "Symptom Clusters in Systemic Sclerosis ABSTRACT\nAn estimated 2.5 million people worldwide are challenged with managing the disfiguring, debilitating, and often\nunremitting symptoms of systemic sclerosis (SSc; scleroderma). SSc is a rare, chronic multisystem\nautoimmune disease that often leads to high levels of pain, fatigue, sleep disturbance, and altered mood (i.e.,\nanxiety and depressive symptoms) as well as significant functional disability. Prior research in SSc has\nfocused on single symptoms and their effects on patient outcomes. However, little is known about the\nprevalence and impact of multiple co-occurring symptoms, or symptom clusters, and their relationship with\nfunctional disability in patients with SSc. The purpose of this study is to understand the distinct symptom\nexperiences of SSc patients with co-occurring symptoms and their relationship with functional disability to\ninform future development of targeted symptom management interventions. This study aims to: 1) identify\nsubgroups of SSc patients with distinct symptom experiences using a prespecified symptom cluster (i.e., pain,\nfatigue, sleep disturbance, and altered mood); 2) determine the individual characteristics (i.e., demographic\nand clinical characteristics) associated with each symptom cluster subgroup; and, 3) determine the extent to\nwhich symptom cluster subgroups predict functional disability. This descriptive cross-sectional study will use\nexisting symptom data collected at enrollment from the Scleroderma Patient-centered Intervention Network\n(SPIN) Cohort (N=1942), including the Patient-Reported Outcomes Measurement Information System-29\n(PROMIS-29) and the Health Assessment Questionnaire Disability Index (HAQ-DI). Latent profile analysis\n(LPA) will be used to identify subgroups of SSc patients with distinct symptom profiles using a prespecified\nsymptom cluster. Bivariate and multiple regression models will be used to determine individual characteristics\nassociated with each symptom cluster subgroup. Finally, a regression model approach will be used to\ndetermine whether subgroup membership is associated with functional disability. The proposed study supports\nthe National Institute of Nursing Research\u2019s mission and area of strategic focus in symptom science by\nproviding a new lens to SSc symptom research to capture the complexities of the symptom experience through\nexploration of multiple co-occurring symptoms, or symptom clusters, and their effects on functional disability in\nSSc. Findings from this study will inform the next stages of symptom science research (i.e., biomarker\ndiscovery and clinical application) in patients with SSc and has the strong potential to inform symptom science\nin other rare diseases."     
    ) 
]

print(model.predict(test_pairs))