from sentence_transformers import CrossEncoder
import torch
from core.search.modal_reranker import rerank_fn

_model = None

RERANK_MODEL_PATH = "./models/rerankers/v5"
device = "cuda" if torch.cuda.is_available() else "cpu"

# lazy initialization to load the model only once

# load model
model = CrossEncoder(RERANK_MODEL_PATH, device=device)

# test_pairs = [
#    ( "multiple sclerosis",  "Multiple System Atrophy - Novel Targets in Early Diagnosis, Pathophysiology, and Therapeutic Approach ABSTRACT\n﻿ DESCRIPTION (provided by applicant): Multiple system atrophy (MSA) is a progressive and fatal neurologic disorder characterized by autonomic failure, parkinsonism, and/or cerebellar ataxia. Consensus criteria for the diagnosis of MSA have improved certitude of diagnosis but have also deferred diagnosis to a later stage of disease. Treatment trials of MSA have been negative in significant part because the disorder could not be diagnosed with certainty until a late stage of disease. An important goal is therefore to identify early, still evolving MSA at a stage when disease activity can be arrested and meaningful recovery is possible. Our proposal is focused on the development of novel biomarkers that will allow us to identify MSA at such an early stage. Firstly, we shall study MSA following diagnosis at the earliest disease stage currently possible (combining consensus criteria with clinical autonomic testing for diagnosis).In this cohort, we will derive and follow a selected set of biomarkers, including MRI morphometry for neuronal loss and spinal fluid biomarkers for central axonal and neuronal degeneration, to identify biomarkers of early MSA (Specific Aim #1). Our second approach involves pure autonomic failure (PAF), a synucleinopathy characterized by severe, progressive autonomic failure. Most patients with PAF survive for decades without clinical central nervous system involvement, but some patients convert to MSA. In our discovery cohort, we have identified highly predictive clinical indicators of conversion to MSA within a two to three year timeframe. We will apply our biomarker approach to patients predicted to evolve from PAF to MSA (Specific Aim #2), follow patients over time, and compare clinical course and biomarkers with stable PAF. This approach enables us to assess the value of the proposed biomarkers and study MSA at an earlier stage than has previously been possible. We are uniquely situated to undertake these studies since our program has access to a large number of patients with both of these rare conditions. Our Autonomic Disorders database, currently has over 300 patients with PAF and over 600 patients with MSA, comprising subjects we have studied over the last 10 years. The findings from this proposal should result in MSA diagnosis at a much earlier stage than has been previously possible. We posit that insights from this approach might eventually allow us to diagnose MSA at an even earlier evolving or preclinical stage of disease. Randomized clinical trials using a novel set of criteria and biomarkers should stand a greater probability of demonstrating efficacy. With Specific Aim #3 of this proposal we shall identify pattern and progression of atrophy of selected brain structures using MRI morphometry which is tightly interconnected with the other two aims."),
#    ( "multiple system atrophy", "Multiple System Atrophy - Novel Targets in Early Diagnosis, Pathophysiology, and Therapeutic Approach ABSTRACT\n﻿ DESCRIPTION (provided by applicant): Multiple system atrophy (MSA) is a progressive and fatal neurologic disorder characterized by autonomic failure, parkinsonism, and/or cerebellar ataxia. Consensus criteria for the diagnosis of MSA have improved certitude of diagnosis but have also deferred diagnosis to a later stage of disease. Treatment trials of MSA have been negative in significant part because the disorder could not be diagnosed with certainty until a late stage of disease. An important goal is therefore to identify early, still evolving MSA at a stage when disease activity can be arrested and meaningful recovery is possible. Our proposal is focused on the development of novel biomarkers that will allow us to identify MSA at such an early stage. Firstly, we shall study MSA following diagnosis at the earliest disease stage currently possible (combining consensus criteria with clinical autonomic testing for diagnosis).In this cohort, we will derive and follow a selected set of biomarkers, including MRI morphometry for neuronal loss and spinal fluid biomarkers for central axonal and neuronal degeneration, to identify biomarkers of early MSA (Specific Aim #1). Our second approach involves pure autonomic failure (PAF), a synucleinopathy characterized by severe, progressive autonomic failure. Most patients with PAF survive for decades without clinical central nervous system involvement, but some patients convert to MSA. In our discovery cohort, we have identified highly predictive clinical indicators of conversion to MSA within a two to three year timeframe. We will apply our biomarker approach to patients predicted to evolve from PAF to MSA (Specific Aim #2), follow patients over time, and compare clinical course and biomarkers with stable PAF. This approach enables us to assess the value of the proposed biomarkers and study MSA at an earlier stage than has previously been possible. We are uniquely situated to undertake these studies since our program has access to a large number of patients with both of these rare conditions. Our Autonomic Disorders database, currently has over 300 patients with PAF and over 600 patients with MSA, comprising subjects we have studied over the last 10 years. The findings from this proposal should result in MSA diagnosis at a much earlier stage than has been previously possible. We posit that insights from this approach might eventually allow us to diagnose MSA at an even earlier evolving or preclinical stage of disease. Randomized clinical trials using a novel set of criteria and biomarkers should stand a greater probability of demonstrating efficacy. With Specific Aim #3 of this proposal we shall identify pattern and progression of atrophy of selected brain structures using MRI morphometry which is tightly interconnected with the other two aims.")
#    ]

# print(model.predict(test_pairs))

query = "multiple sclerosis"
doc = "Multiple System Atrophy - Novel Targets in Early Diagnosis, Pathophysiology, and Therapeutic Approach ABSTRACT\n﻿ DESCRIPTION (provided by applicant): Multiple system atrophy (MSA) is a progressive and fatal neurologic disorder characterized by autonomic failure, parkinsonism, and/or cerebellar ataxia. Consensus criteria for the diagnosis of MSA have improved certitude of diagnosis but have also deferred diagnosis to a later stage of disease. Treatment trials of MSA have been negative in significant part because the disorder could not be diagnosed with certainty until a late stage of disease. An important goal is therefore to identify early, still evolving MSA at a stage when disease activity can be arrested and meaningful recovery is possible. Our proposal is focused on the development of novel biomarkers that will allow us to identify MSA at such an early stage. Firstly, we shall study MSA following diagnosis at the earliest disease stage currently possible (combining consensus criteria with clinical autonomic testing for diagnosis).In this cohort, we will derive and follow a selected set of biomarkers, including MRI morphometry for neuronal loss and spinal fluid biomarkers for central axonal and neuronal degeneration, to identify biomarkers of early MSA (Specific Aim #1). Our second approach involves pure autonomic failure (PAF), a synucleinopathy characterized by severe, progressive autonomic failure. Most patients with PAF survive for decades without clinical central nervous system involvement, but some patients convert to MSA. In our discovery cohort, we have identified highly predictive clinical indicators of conversion to MSA within a two to three year timeframe. We will apply our biomarker approach to patients predicted to evolve from PAF to MSA (Specific Aim #2), follow patients over time, and compare clinical course and biomarkers with stable PAF. This approach enables us to assess the value of the proposed biomarkers and study MSA at an earlier stage than has previously been possible. We are uniquely situated to undertake these studies since our program has access to a large number of patients with both of these rare conditions. Our Autonomic Disorders database, currently has over 300 patients with PAF and over 600 patients with MSA, comprising subjects we have studied over the last 10 years. The findings from this proposal should result in MSA diagnosis at a much earlier stage than has been previously possible. We posit that insights from this approach might eventually allow us to diagnose MSA at an even earlier evolving or preclinical stage of disease. Randomized clinical trials using a novel set of criteria and biomarkers should stand a greater probability of demonstrating efficacy. With Specific Aim #3 of this proposal we shall identify pattern and progression of atrophy of selected brain structures using MRI morphometry which is tightly interconnected with the other two aims."

query2 = "multiple system atrophy"


print("CrossEncoder score for query-doc pair:")
print(model.predict([(query, doc)]))


print("CrossEncoder score for query2-doc pair:")
print(model.predict([(query2, doc)]))


print("modal reranker score for query-doc pair:")
score = rerank_fn.remote(query, [doc])
print(score)

print("modal reranker score for query2-doc pair:")
score = rerank_fn.remote(query2, [doc])
print(score)
