import time
from datetime import datetime

def extract_funding(results: dict) -> tuple[list[int], list[float]]:
    """
    Extracts and scales yearly funding totals from search results, adjusting for the current fiscal year.

    Parameters
    ----------
    results : dict
        A dictionary containing search results, including a list of records with fiscal year and amount information.

    Returns
    -------
    tuple[list[int], list[float]]
        A tuple containing two lists:
        - A list of fiscal years (int).
        - A list of corresponding scaled funding amounts (float) for each fiscal year.

    """
 
    yearly_totals = {}
    now = datetime.now()
    current_fy = now.year if now.month < 10 else now.year + 1
    months_elapsed = (now.month - 10) % 12 + 1
    scaling_factor = 12/months_elapsed

    print(f"Current fiscal year: {current_fy}, months elapsed: {months_elapsed}, scaling factor: {scaling_factor}")
    for r in results["records"]:
        yr = r["fiscal_year"]
        
        amt = r["amount"] or 0 
        yearly_totals[yr] = yearly_totals.get(yr, 0) + amt

    if current_fy in yearly_totals:
        yearly_totals[current_fy] *= scaling_factor
    years = sorted(yearly_totals.keys())

    funding = [yearly_totals[yr] for yr in years]

    return years, funding

def extract_ontology_distribution(results: dict) -> tuple[list[str], list[float]]:
    """
    Calculates the total funding distribution across abstract categories (generated by LLM) from search results.

    Parameters
    ----------
    results : dict
        A dictionary containing search results, including a list of records with category and amount information.

    Returns
    -------
    tuple[list[str], list[float]]
        A tuple containing two lists:
        - A list of category display names (str).
        - A list of corresponding total funding amounts (float) for each category.

    """

    labels = [
        ("Mechanistic / Basic Science", "mechanistic"),
        ("Therapeutic", "therapeutic"),
        ("Diagnostic", "diagnostic"),
        ("Research Tool", "research_tool"),
        ("Clinical / Health Systems", "clinical"),
        ("Research Infrastructure", "infrastructure"),
        ("Education / Training", "education"),
        ("Observational Epidemiology", "obs_ep")
    ]

    totals = {}
    for display_name, key in labels:
        total = 0
        for r in results["records"]:
            if r.get(key)==1:
                total += r.get("amount") or 0
        totals[display_name] = total

    return list(totals.keys()), list(totals.values())

def format_output_grants(ranked_docs: list[dict]) -> list[dict]:

    """
    Helper layout to normalize object fields perfectly for JavaScript render tracks

    Parameters
    ----------
    ranked_docs : list[dict]
        A list of dictionaries representing ranked grant documents, each containing various fields such as organization name, funding amount, and principal investigator information.

    Returns
    -------
    list[dict]
        A list of dictionaries with normalized fields for JavaScript rendering, including organization name, funding amount, and principal investigator information.

    """

    for g in ranked_docs:
        g["organization"] = g.get("org_name")
        g["funding"] = g.get("amount")
        first, middle, last = g.get("pi_first_name") or "", g.get("pi_middle_name") or "", g.get("pi_last_name") or ""
        g["pi"] = " ".join(x for x in [first, middle, last] if x)
    return ranked_docs
