# This script contains functions to create and interact with the database tables for NIH grant data

from core.ingest.normalize import normalize_name

# Creates the Organizations table to store information about organizations.

def create_organizations_table(cur):
    cur.execute('''
        CREATE TABLE IF NOT EXISTS Organizations (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
        name TEXT,
        city TEXT,
        state TEXT,
        country TEXT,
        UNIQUE(name,city,state,country)            
        )''')

# Creates the ResearchGrants table to store information about research grants.

def create_research_grants_table(cur):
    cur.execute('''
        CREATE TABLE IF NOT EXISTS ResearchGrants (
        grant_id TEXT PRIMARY KEY, 
        fiscal_year INTEGER NOT NULL, 
        project_num TEXT NOT NULL,
        subproject_id TEXT,
        core_project_num TEXT NOT NULL,            
        contact_pi_id TEXT,
        organization_id INTEGER,
        project_start_date DATE,
        project_end_date DATE,
        budget_start_date DATE,
        budget_end_date DATE NOT NULL,
        project_title TEXT NOT NULL,
        abstract TEXT,
        phr TEXT,
        agency_ic TEXT,
        total_award_amount REAL DEFAULT 0.0,
        org_resolution_status TEXT,
        ingest_id TEXT,
        content_hash TEXT,
        record_version INTEGER DEFAULT 1,
        record_updated_at TIMESTAMP,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             
        FOREIGN KEY(organization_id) REFERENCES Organizations (id)       
        )''')


# Creates the PIs table to store information about principal investigators.

def create_pis_table(cur):
    cur.execute('''
        CREATE TABLE IF NOT EXISTS PIs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
        canonical_name TEXT NOT NULL UNIQUE,
        first_name TEXT,
        middle_name TEXT,
        last_name TEXT            
        )''')

# Creates the RGrantPIs table to associate research grants with principal investigators.

def create_rgrant_pis_table(cur):
    cur.execute('''
        CREATE TABLE IF NOT EXISTS RGrantPIs (
        grant_id TEXT,  
        pi_id INTEGER,
        is_contact_pi BOOLEAN,
        PRIMARY KEY (grant_id, pi_id),
        FOREIGN KEY(grant_id) REFERENCES ResearchGrants(grant_id),
        FOREIGN KEY(pi_id) REFERENCES PIs(id)   
        )''')
# Creates the IngestRuns table to track the status and metrics of each ingest run.

def create_ingest_runs_table(cur):
    
    cur.execute('''
        CREATE TABLE IF NOT EXISTS IngestRuns (
            ingest_id TEXT PRIMARY KEY,
            started_at TIMESTAMP NOT NULL,
            completed_at TIMESTAMP,
            num_inserted INTEGER DEFAULT 0,
            num_updated INTEGER DEFAULT 0,
            num_skipped INTEGER DEFAULT 0,
            num_errors INTEGER DEFAULT 0,
            status TEXT,
            notes TEXT
        ); ''')
# Creates the IngestErrors table to record errors encountered during the ingest process for specific grants.

def create_ingest_errors_table(cur):
    cur.execute('''
    CREATE TABLE IF NOT EXISTS IngestErrors (
    ingest_id TEXT,
    grant_id TEXT,
    error_type TEXT,
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );''')

# Creates the GrantEmbeddings table to store embeddings for each grant.

def create_grant_embeddings_table(cur):
    cur.execute('''
    CREATE TABLE IF NOT EXISTS GrantEmbeddings (
    grant_id TEXT PRIMARY KEY,
    content_hash TEXT NOT NULL,
    embedding vector(768),
    embedding_model TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_valid BOOLEAN DEFAULT TRUE
    );''')


def insert_organization(cur, org: dict) -> int:
   
    # Inserts an organization into the database if it doesn't already exist.
    # Returns the organization ID.
    
    orgname = org.get("name") or ""
    orgcity = org.get("city") or "" 
    orgstate = org.get("state") or ""
    orgcountry = org.get("country") or ""


    cur.execute(''' INSERT INTO Organizations (name, city, state , country) 
                    VALUES(%s, %s, %s, %s)
                    ON CONFLICT(name, city, state, country) DO NOTHING
                    RETURNING id;
                    ''', (orgname, orgcity, orgstate, orgcountry))

    cur.execute(
        '''SELECT id FROM Organizations
           WHERE name = %s
             AND city = %s
             AND country = %s
             AND (state = %s
                  OR (state IS NULL AND %s = '')
                  OR (state IS NULL AND %s IS NULL))''',
        (orgname, orgcity, orgcountry, orgstate, orgstate, orgstate)
    )
    row = cur.fetchone()
    if not row:
        raise ValueError(f"Failed to insert or find organization")
    return row[0]

def insert_research_grant(cur, result: dict, core_project_num: str, org_id: int, org_resolution_status:str, ingest_id:str, content_hash: str):
    
    # Inserts a research grant into the database.
    #Returns the grant ID.
    
    project_num = result.get("project_num")
    sub_id = result.get("subproject_id")
    grant_id = f"{project_num}-{sub_id}" if sub_id else project_num

    projstartdate = result.get('project_start_date')
    projenddate = result.get('project_end_date')
    budgstartdate = result.get('budget_start')
    budgenddate = result.get('budget_end')
    contactpiname = result.get('contact_pi_name') #this will be last name comma first name middle initial w/without a period

    cur.execute('''
                INSERT INTO ResearchGrants(grant_id, fiscal_year, project_num, subproject_id,core_project_num,
                contact_pi_id, organization_id, project_start_date, project_end_date, budget_start_date, budget_end_date, 
                project_title, abstract, phr, agency_ic, total_award_amount, org_resolution_status, ingest_id, content_hash, record_version, record_updated_at) 
                VALUES (%s, %s, %s, %s, %s,%s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,%s,%s, 1, CURRENT_TIMESTAMP)
                ON CONFLICT (project_num, subproject_id)
                DO UPDATE SET
                    fiscal_year          = EXCLUDED.fiscal_year,
                    contact_pi_id        = EXCLUDED.contact_pi_id,
                    organization_id      = EXCLUDED.organization_id,
                    total_award_amount   = EXCLUDED.total_award_amount,
                    project_end_date     = EXCLUDED.project_end_date,
                    budget_start_date    = EXCLUDED.budget_start_date,
                    budget_end_date      = EXCLUDED.budget_end_date,
                    project_title        = EXCLUDED.project_title,
                    abstract             = EXCLUDED.abstract,
                    phr                  = EXCLUDED.phr,
                    agency_ic            = EXCLUDED.agency_ic,
                    total_award_amount   = EXCLUDED.total_award_amount,
                    org_resolution_status= EXCLUDED.org_resolution_status,
                    ingest_id            = EXCLUDED.ingest_id,
                    record_version       = record_version + 1,
                    record_updated_at    = CURRENT_TIMESTAMP
                WHERE content_hash IS DISTINCT FROM EXCLUDED.content_hash                
                ''',
                (grant_id, result.get('fiscal_year'),project_num, sub_id,core_project_num,(result.get('contact_pi_name')or "").title(),org_id,
                projstartdate.split("T")[0] if projstartdate else None, projenddate.split("T")[0] if projenddate else None, budgstartdate.split("T")[0] if budgstartdate else None, 
                budgenddate.split("T")[0] if budgenddate else None, result.get('project_title'), result.get('abstract_text'), result.get('phr_text'),
                    result.get("agency_ic_admin",{}).get("name"), result.get('award_amount'), org_resolution_status, ingest_id, content_hash))

def update_research_grant(cur, result: dict, grant_id:str, ingest_id:str, content_hash: str, record_version):
    
    cur.execute('''
                UPDATE ResearchGrants
                SET project_title = %s,
                    abstract = %s,
                    phr = %s, 
                    total_award_amount = %s,
                    content_hash = %s,
                    record_version = %s, 
                    record_updated_at = CURRENT_TIMESTAMP,
                    ingest_id = %s
                WHERE project_num = %s
                AND subproject_id IS NOT DISTINCT FROM %s''',
                (result.get('project_title'), result.get('abstract_text'), result.get('phr_text'), 
                 result.get('award_amount'), content_hash, record_version + 1, ingest_id, result.get('project_num'), result.get('subproject_id'))) 


def insert_pis(cur, grant_id: str, pis: list):
    
    # Inserts principal investigators into the database and links them to the research grant.
    
    for investigator in pis:
        
        # Normalize the investigator's name to extract first, middle, last, and canonical forms

        first, middle, last, canonical = normalize_name(investigator.get("full_name"))

        if not canonical:
            continue
        
        # Insert the PI into the database, or update if they already exist
        cur.execute("""
                INSERT INTO PIs (canonical_name, first_name, middle_name, last_name)
                VALUES (%s, %s, %s, %s) RETURNING id",
                ON CONFLICT (canonical_name) DO UPDATE 
                SET canonical_name = EXCLUDED.canonical_name -- This is a trick to force a RETURNING id
                RETURNING id
                """, (canonical, first, middle, last))

        row = cur.fetchone()
        if not row:
            cur.execute("SELECT id FROM PIs WHERE canonical_name = %s", (canonical,))
               
        else:
            pi_id = row[0] 

        # Link the PI to the research grant
        cur.execute("""
            INSERT INTO RGrantPIs (grant_id, pi_id, is_contact_pi) 
            VALUES (%s,%s,%s)
            ON CONFLICT(grant_id, pi_id) 
            DO UPDATE SET is_contact_pi = EXCLUDED.is_contact_pi
            """, (grant_id, pi_id, investigator.get("is_contact_pi")))

def insert_ingest_run(cur, ingest_id: str):
    
    # Inserts a new ingest run record into the database.
    
    cur.execute(
        """
        INSERT INTO IngestRuns (ingest_id, started_at, status)
        VALUES (%s, CURRENT_TIMESTAMP, 'running')
        """,
        (ingest_id,)
    )

def update_ingest_run_status(cur, ingest_id: str, metrics: dict):
    
    # Updates the status of an ingest run record in the database.
   

    cur.execute(
        """
        UPDATE IngestRuns
        SET completed_at = CURRENT_TIMESTAMP,
            status = 'completed',
            num_inserted = %s,
            num_updated = %s,
            num_skipped = %s,
            num_errors = %s
        WHERE ingest_id = %s
        """,
        (metrics["num_inserted"], metrics["num_updated"], metrics["num_skipped"], metrics["num_errors"], ingest_id)
    )
# Marks an ingest run as failed and records the error message.
def mark_ingest_run_failed(cur, ingest_id: str, error_message: str):
    cur.execute(
        """
        UPDATE IngestRuns
        SET
            status = 'failed',
            completed_at = CURRENT_TIMESTAMP,
            notes = %s
        WHERE ingest_id = %s
        """,
        (error_message[:1000], ingest_id)  # truncate defensively
    )

# Records an error encountered during the ingest process for a specific grant.
def record_error(cur, ingest_id, grant_id, error_type, message):
    cur.execute(
        """
        INSERT INTO IngestErrors
        (ingest_id, grant_id, error_type, error_message)
        VALUES (%s, %s, %s, %s)
        """,
        (ingest_id, grant_id, error_type, message)
    )
# Marks the embeddings for a specific grant as invalid.
def update_grant_embeddings(cur, grant_id: str):
    cur.execute('''
        UPDATE GrantEmbeddings
        SET is_valid = FALSE
        WHERE grant_id = %s''',
        (grant_id,))

