def load_grant_embeddings_and_text(cur, grant_ids, active_lens="topic"):
    if not grant_ids:
        return []

    # 1. CHOOSE THE RIGHT SQL QUERY STRUCTURE BASED ON THE ACTIVE LENS
    if active_lens == "career_stage":
        # 🚀 Use the fractional multi-PI splitting logic for accurate workforce analytics
        query = """
        WITH PI_Vintages AS (
            SELECT 
                rgp.pi_id,
                MIN(EXTRACT(YEAR FROM g.project_start_date)) AS first_award_year
            FROM rgrantpis rgp
            JOIN ResearchGrants g ON rgp.grant_id = g.grant_id
            GROUP BY rgp.pi_id
        ),
        Grant_PI_Weights AS (
            SELECT 
                grant_id,
                COUNT(pi_id) AS pi_count
            FROM rgrantpis
            GROUP BY grant_id
        )
        SELECT 
            rg.grant_id,
            rg.project_title AS title,
            rg.abstract AS abstract_text,
            (rg.total_award_amount / COALESCE(w.pi_count, 1)) AS amount,
            rg.agency_code,
            o.state AS org_state,
            ge.embedding,
            gl.mechanistic, gl.therapeutic, gl.diagnostic, gl.research_tool,
            gl.clinical, gl.infrastructure, gl.education, gl.obs_ep,
            CASE 
                WHEN v.first_award_year >= 2022 THEN 'Early-Career Vanguard'
                WHEN v.first_award_year BETWEEN 2015 AND 2021 THEN 'Mid-Career Pivot'
                ELSE 'Legacy Tenured Anchor'
            END AS career_stage
        FROM ResearchGrants rg
        JOIN grant_labels gl ON rg.grant_id = gl.grant_id
        INNER JOIN GrantEmbeddings ge ON rg.grant_id = ge.grant_id
        LEFT JOIN organizations o ON rg.organization_id = o.id
        JOIN rgrantpis rgp ON rg.grant_id = rgp.grant_id
        JOIN PI_Vintages v ON rgp.pi_id = v.pi_id
        LEFT JOIN Grant_PI_Weights w ON rg.grant_id = w.grant_id
        WHERE rg.grant_id = ANY(%s)
        """
    else:
        # 🏢 Standard query for all other lenses (with fixed SQL aliases applied)
        query = """
        SELECT 
            rg.grant_id,
            rg.project_title AS title,
            rg.abstract AS abstract_text,
            rg.total_award_amount AS amount,
            rg.agency_code,
            o.state AS org_state,
            ge.embedding,
            gl.mechanistic, gl.therapeutic, gl.diagnostic, gl.research_tool,
            gl.clinical, gl.infrastructure, gl.education, gl.obs_ep,
            'Unclassified' AS career_stage
        FROM ResearchGrants rg
        JOIN grant_labels gl ON rg.grant_id = gl.grant_id
        INNER JOIN GrantEmbeddings ge ON rg.grant_id = ge.grant_id
        LEFT JOIN organizations o ON rg.organization_id = o.id
        WHERE rg.grant_id = ANY(%s)
        """

    cur.execute(query, (grant_ids,))
    rows = cur.fetchall()

    # 2. POPULATE THE DOCS DICTIONARY SAFELY VIA COLUMN POSITION
    docs = []
    
    for r in rows:
        # Unpack positionally using the exact alias footprint generated by both queries
        gid = r[0]
        title = r[1]
        abstract = r[2]
        amount = r[3]
        agency_code = r[4]
        org_state = r[5]
        embedding = r[6]
        
        if isinstance(embedding, str):
            import json
            embedding = json.loads(embedding)

        docs.append({
            "grant_id": gid,
            "title": title,
            "abstract": abstract,
            "amount": amount,
            "agency_code": agency_code,
            "org_state": org_state,
            "embedding": embedding,
            "mechanistic": r[7],
            "therapeutic": r[8],
            "diagnostic": r[9],
            "research_tool": r[10],
            "clinical": r[11],
            "infrastructure": r[12],
            "education": r[13],
            "obs_ep": r[14],
            "career_stage": r[15] # 👈 Safely map the career stage flag downstream
        })

    return docs